try{

    hello()
    
}catch(error){

    console.error(error)

}

try{

    anotherFunction()

}catch{

    console.error('esto es un error')

}